# Generated by Django 3.2.8 on 2022-01-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='photo',
            new_name='photo',
        ),
    ]
